name: scrape

services:
  postgres:
    image: postgres:17
    container_name: scrape-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: scrape
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    ports:
      - '5433:5432'
    volumes:
      - scrape-db-data:/var/lib/postgresql/data

volumes:
  scrape-db-data:
